config/routes.rb
RdsPrototype::Application.routes.draw do

  get "/data-group", :to => 'data_group#index', :as => :data_group_index

  scope '/lead-scoring', :as => :lead_scoring do
    get "/", :to => 'lead_scoring#index', :as => :index
    get "/analisar", :to => 'lead_scoring#show', :as => :show
    scope "/configurar", :as => :rules do
      get '/' => redirect("/lead-scoring/configurar/perfil"), :as => :index
      get "/perfil", :to => 'lead_scoring#rules_fit', :as => :fit
      get "/interesse", :to => 'lead_scoring#rules_interest', :as => :interest
      get "/segmentacao", :to => 'lead_scoring#rules_segmentation', :as => :segmentation
      get "/automacao", :to => 'lead_scoring#rules_automation', :as => :automation
    end
    get "/avaliar", :to => 'lead_scoring#stats', :as => :stats
  end

  root to: "home#index"

  get "home/index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/data_group_controller.rb
class DataGroupController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lead_scoring_controller.rb
class LeadScoringController < ApplicationController

  layout false

  def index
    render layout: "application"
  end

  def show
    render layout: "application"
  end

  def rules
    render layout: "application"
  end

  def rules_fit
    @fit_terms = "fit_terms.new"
    # 2.times { @fit_terms.fit_terms.build}
    render layout: "lead_scoring/rules"
  end

  def rules_interest
    render layout: "lead_scoring/rules"
  end

  def rules_segmentation
    render layout: "lead_scoring/rules"
  end

  def rules_automation
    render layout: "lead_scoring/rules"
  end

  def stats
    render layout: "application"
  end

  def settings
    render layout: "application"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_group_helper.rb
module DataGroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lead_scoring_helper.rb
module LeadScoringHelper

  def active_tab(controller, item)
    controller.split("/").last == item ? 'active': ''
  end

end

app/views/data_group/_landing-page.html.erb
<% content_for :header do %>
  <%#= stylesheet_link_tag 'landing_pages' %>
<% end %>

<div class="container">
  <span id="js-lp-link"><span class="text-muted" id="js-lp-link">http://pages.rdstation.com.br/68a869e27bc651ade405</span></span>
  <div id="data-wrapper" class="resume"><hr> <div class="row"> 	<div class="col-xs-3"> 		<div class="data-group"> 			<div class="data-group-value size-a">0</div> 			<div class="data-group-label">Visitantes</div> 		</div> 	</div> 	<div class="col-xs-1">     <i class="data-arrow-right"></i>   </div> 	<div class="col-xs-3"> 		<div class="data-group"> 			<div class="data-group-value size-a">0%</div> 			<div class="data-group-label">Taxa de conversão</div> 		</div> 	</div> 	<div class="col-xs-1"> 		<i class="data-arrow-right"></i> 	</div> 	<div class="col-xs-4"> 		<div class="data-group"> 			<div class="data-group-value size-a"> 				<a href="/leads?query=evento%3A%2268a869e27bc651ade405%22" title="Clique aqui para ver sua Base de Leads (CRM)"> 					0 				</a> 			</div> 			<div class="data-group-label">Leads</div> 		</div> 	</div> </div> <hr> </div>
  <div class="row promove">
    <div class="col-xs-6">
      <h4>Promover em Mídias Sociais</h4>
      <a href="/agendamento/novo?content=094+-+Duplicado%3A+http%3A%2F%2Fpages.rdstation.com.br%2F68a869e27bc651ade405" class="btn btn-default" data-remote="true" id="new_post_link" title="Criar nova publicação">Criar nova publicação</a>
    </div>
    <div class="col-xs-6">
      <h4>Promover por email</h4>
      <a href="/campanhas/nova" class="btn btn-default" data-loading-text="Aguarde">Criar nova campanha</a>
    </div>
  </div>
</div>

<!-- $font-size-xsmall: 13px;
$font-size-msmall: -;
$font-size-small:  14px;
$font-size-base:   16px;
$font-size-medium: 18px;
$font-size-large:  20px;
$font-size-mlarge: 27px;
$font-size-xlarge: 32px;


data-group {
  .data-title {
    font-size: $font-size-large; //20
    line-height: 1.8em; //36
    display: inline-block;
  }
  .data-value {
    font-size: $font-size-large; //20
    line-height: 1.8em; //21
    display: inline-block;
    small {
      font-size: $font-size-small;
    }
  }
  .data-label {
    font-size: $font-size-small; //14
    line-height: 1.8em; //15
    display: inline-block;
  }
} -->

app/views/data_group/_lead-scoring-fit.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'lead_scoring' %>
<% end %>

lead-scoring-fit

app/views/data_group/_lead-scoring-home.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'lead_scoring' %>
<% end %>

lead-scoring-home

app/views/data_group/_lead-scoring-interest.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'lead_scoring' %>
<% end %>

lead-scoring-interest

app/views/data_group/_marketing-bi-campanhas.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'advanced_analytics/advanced' %>
<% end %>

marketing-bi-campanhas

app/views/data_group/_marketing-bi-canais-de-aquisicao.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'advanced_analytics/advanced' %>
<% end %>

marketing-bi-canais-de-aquisicao

app/views/data_group/_marketing-bi-negocios-planejamento.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'advanced_analytics/advanced' %>
<% end %>

marketing-bi-negocios-planejamento

app/views/data_group/_painel-de-palavras-chave.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'keywords_panel' %>
<% end %>

painel-de-palavras-chave

app/views/data_group/index.html.erb
<% content_for :pagetitle do %>
  DataGroup CSS Component
<% end %>

<% content_for :pagesubtitle do %>
  <div class="row">
    <div class="col-xs-9">
      <h2><span class="text-muted">Exemplo</span> <span class="showactive">automacao-de-marketing</span></h2>
    </div>
    <div class="col-xs-3 action-header">
      <div class="btn-group pull-right">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          escolha o exemplo <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li class="active"><a class="trigger-choose-version" href="#" data-target="automacao-de-marketing">automação de marketing</a></li>
          <li><a class="trigger-choose-version" href="#" data-target="base-de-leads">base de leads</a></li>
          <li><a class="trigger-choose-version" href="#" data-target="campanhas">campanhas</a></li>
          <li><a class="trigger-choose-version" href="#" data-target="landing-page">landing page</a></li>
          <li><a class="trigger-choose-version" href="#" data-target="lead-scoring-fit">lead scoring - perfil</a></li>
          <li><a class="trigger-choose-version" href="#" data-target="lead-scoring-home">lead scoring - home</a></li>
          <li><a class="trigger-choose-version" href="#" data-target="lead-scoring-interest">lead scoring - interesse</a></li>
          <li><a class="trigger-choose-version" href="#" data-target="marketing-bi-campanhas">marketing bi - campanhas</a></li>
          <li><a class="trigger-choose-version" href="#" data-target="marketing-bi-canais-de-aquisicao">marketing bi - canais de aquisição</a></li>
          <li><a class="trigger-choose-version" href="#" data-target="marketing-bi-negocios-planejamento">marketing bi - negócios/planejamento</a></li>
          <li><a class="trigger-choose-version" href="#" data-target="marketing-bi-negocios-resultados">marketing bi - negócios/resultados</a></li>
          <li><a class="trigger-choose-version" href="#" data-target="painel-de-palavras-chave">painel de palavras chave</a></li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<div class="mayhideshow automacao-de-marketing">
<%= render :partial => 'data_group/automacao-de-marketing' %>
</div>
<div class="mayhideshow base-de-leads hide">
<%= render :partial => 'data_group/base-de-leads' %>
</div>
<div class="mayhideshow campanhas hide">
<%= render :partial => 'data_group/campanhas' %>
</div>
<div class="mayhideshow landing-page hide">
<%= render :partial => 'data_group/landing-page' %>
</div>
<div class="mayhideshow lead-scoring-fit hide">
<%= render :partial => 'data_group/lead-scoring-fit' %>
</div>
<div class="mayhideshow lead-scoring-home hide">
<%= render :partial => 'data_group/lead-scoring-home' %>
</div>
<div class="mayhideshow lead-scoring-interest hide">
<%= render :partial => 'data_group/lead-scoring-interest' %>
</div>
<div class="mayhideshow marketing-bi-canais-de-aquisicao hide">
<%= render :partial => 'data_group/marketing-bi-canais-de-aquisicao' %>
</div>
<div class="mayhideshow marketing-bi-negocios-planejamento hide">
<%= render :partial => 'data_group/marketing-bi-negocios-planejamento' %>
</div>
<div class="mayhideshow marketing-bi-negocios-resultados hide">
<%= render :partial => 'data_group/marketing-bi-negocios-resultados' %>
</div>
<div class="mayhideshow painel-de-palavras-chave hide">
<%= render :partial => 'data_group/painel-de-palavras-chave' %>
</div>

<% content_for :footer do %>
<script type="text/javascript">
  $(function(){
    $('.trigger-choose-version').live('click', function(){
      $('.mayhideshow').addClass('hide');
      var idPanelPlanning = $(this).data('target');
      $('.trigger-choose-version').parent().removeClass('active');
      $(this).parent().addClass('active');
      $('.'+idPanelPlanning).removeClass('hide');
      $('.showactive').html(idPanelPlanning);
    });
  });
</script>
<% end %>

app/views/home/index.html.erb
<% content_for :header do %>
<% end %>

<% content_for :pagetitle do %>
  home, sweet home
<% end %>

<% content_for :pagesubtitle do %>
<h2><span class="text-muted">Campanha</span> prototipando o rdstation</h2>
<% end %>

<div class="container">

  <form class="form-inline">
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-9">
        <h4 class="panel-title">Nonono nono nonononono non</h4>
      </div>
      <div class="col-xs-3 text-right">
        <a href="#" class="panel-heading-btn action-config" ></a>
        <a href="#" class="panel-heading-btn action-remove" ></a>
      </div>
    </div>
  </div>
  <div class="panel-body panel-conditional-flow">
    <div class="loading">
      <div class="progress">
        <div class="progress-bar progress-bar-striped active"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
          <span class="sr-only">45% Complete</span>
        </div>
      </div>
    </div>
  </div>
</div>
</form>

<div class="progress">
  <div class="progress-bar progress-bar-striped active"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
    <span class="sr-only">45% Complete</span>
  </div>
</div>

</div>

app/views/layouts/_favicons.html.erb
	<!-- Basic favicons -->
	<!-- IMPORTANT! Don't change the order of favicons... -->
	<%= favicon_link_tag "favicon.ico", rel: "shortcut icon", sizes: "16x16 32x32 48x48 64x64", type: nil %>
	<%= favicon_link_tag "favicon.ico", rel: "shortcut icon", type: "image/x-icon" %>
	<!--[if IE]><%= favicon_link_tag "favicon.ico", type: nil %><![endif]-->
	<!-- For Opera Speed Dial -->
	<%= favicon_link_tag "favicon-195.png", rel: "icon", type: "image/png", sizes: "195x195" %>
	<!-- For iPad with high-resolution Retina Display running iOS ≥ 7 -->
	<%= favicon_link_tag "favicon-152.png", rel: "apple-touch-icon", sizes: "152x152", type: nil %>
	<!-- For iPad with high-resolution Retina Display running iOS ≤ 6 -->
	<%= favicon_link_tag "favicon-144.png", rel: "apple-touch-icon", sizes: "144x144", type: nil %>
	<!-- For iPhone with high-resolution Retina Display running iOS ≥ 7 -->
	<%= favicon_link_tag "favicon-120.png", rel: "apple-touch-icon", sizes: "120x120", type: nil %>
	<!-- For iPhone with high-resolution Retina Display running iOS ≤ 6 -->
	<%= favicon_link_tag "favicon-114.png", rel: "apple-touch-icon", sizes: "114x114", type: nil %>
	<!-- For Google TV devices -->
	<%= favicon_link_tag "favicon-96.png", rel: "icon", type: "image/png", sizes: "96x96" %>
	<!-- For iPad Mini -->
	<%= favicon_link_tag "favicon-76.png", rel: "apple-touch-icon", type: "image/png", sizes: "76x76" %>
	<!-- For first- and second-generation iPad -->
	<%= favicon_link_tag "favicon-72.png", rel: "apple-touch-icon", sizes: "72x72", type: nil %>
	<!-- For non-Retina iPhone, iPod Touch and Android 2.1+ devices -->
	<%= favicon_link_tag "favicon-57.png", rel: "apple-touch-icon", type: nil %>
	<!-- Windows 8 Tiles -->
	<meta name="msapplication-TileColor" content="#FFFFFF">
	<meta name="msapplication-TileImage" content="assets/favicon-144.png">

app/views/layouts/_flash.html.erb
<script type="text/javascript">
$(function() {
	// $.bootstrapGrowl("rá", {
	// 	type: 'danger',
	// 	width: 600,
	// 	allow_dismiss: true,
	// });
});
</script>

app/views/layouts/_footer.html.erb
<!-- order matters -->
<%= javascript_include_tag 'application' %>

<%= yield :footer %>

app/views/layouts/_header.html.erb
	<meta charset="utf-8" />
	<title>RD Station</title>

	<%= render :partial => 'layouts/favicons' %>

	<%= csrf_meta_tags %>

	<!-- order matters -->
	<%= stylesheet_link_tag 'application' %>
	<%= yield :header %>

	<!--[if lt IE 9]>
	<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

app/views/layouts/_page_header.html.erb
<header id="page-header" class="container">
  <h1><%= yield :pagetitle %></h1>
  <%= yield :pagehelper %>
  <%= yield :pagesubtitle %>
  <%= yield :pageaction %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= render :partial => 'layouts/header' %>
	<%= yield :head %>
</head>
<body>
	<%= render :partial => 'layouts/navbar' %>
	<section id="content">
		<%= render :partial => 'layouts/page_header' %>
		<%= content_for?(:content) ? yield(:content) : yield  %>
	</section>
	<%= render :partial => 'layouts/footer' %>
	<div id="flash">
		<%= render :partial => 'layouts/flash', :locals => { :flash => flash } %>
	</div>
</body>
</html>

app/views/layouts/lead_scoring/rules.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'lead_scoring' %>
<% end %>

<% content_for :pagetitle do %>
  <%= link_to "Lead Scoring", lead_scoring_index_path %>
<% end %>

<% content_for :pagesubtitle do %>
  <h2>Editar</h2>
<% end %>

<% content_for :content do %>
  <div class="container">
    <%= render :partial => 'lead_scoring/rules_navbar' %>
    <%= yield %>
  </div>
  <%= yield :actions_footer %>
<% end %>

<% content_for :footer do %>
  <%= javascript_include_tag "lead_scoring", async: true %>
<% end %>

<%= render :template => "layouts/application" %>

app/views/lead_scoring/_rules_navbar.html.erb
<div class="container-nav-pills hide">
  <ul class="nav nav-pills">
    <li class="<%= active_tab(request.fullpath, 'perfil') %>"><%= link_to "Perfil", lead_scoring_rules_fit_path %></li>
    <li class="<%= active_tab(request.fullpath, 'interesse') %>"><%= link_to "Interesse", lead_scoring_rules_interest_path %></li>
    <li class="<%= active_tab(request.fullpath, 'segmentacao') %>"><%= link_to "Segmentação", lead_scoring_rules_segmentation_path %></li>
    <li class="<%= active_tab(request.fullpath, 'automacao') %>"><%= link_to "Automação", lead_scoring_rules_automation_path %></li>
  </ul>
</div>

<div class="steps-wrapper ">
  <ul class="steps">
    <li class="<%= active_tab(request.fullpath, 'perfil') %>"><span><%= link_to "Perfil", lead_scoring_rules_fit_path %></span></li>
    <li class="<%= active_tab(request.fullpath, 'interesse') %>"><span><%= link_to "Interesse", lead_scoring_rules_interest_path %></span></li>
    <li class="<%= active_tab(request.fullpath, 'segmentacao') %>"><span>Segmentação<%#= link_to "Segmentação", lead_scoring_rules_segmentation_path %></span></li>
    <li class="<%= active_tab(request.fullpath, 'automacao') %>"><span>Automação<%#= link_to "Automação", lead_scoring_rules_automation_path %></span></li>
  </ul>
</div>

app/views/lead_scoring/rules_automation.html.erb
<p>automation</p>

app/views/lead_scoring/rules_fit.html.erb
<div class="row">
  <div class="col-xs-3">
    <p class="help-block">Alinhe junto ao seu time de vendas quais as propriedades que melhor representam um Lead pronto para venda.</p>
    <p class="help-block">Você também pode utilizar os dados do <%= link_to "Marketing BI", "" %> para descobrir os termos mais relevantes entre os seus clientes para cada propriedade.</p>
  </div>
  <div class="col-xs-9">
    <form class="form-inline">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-6">
              <h3 class="panel-title">Propriedade</h3>
            </div>
            <div class="col-xs-4">
              <h3 class="panel-title">Peso</h3>
            </div>
            <div class="col-xs-2 text-right">
              <button type="button" class="panel-heading-btn popover-info" data-toggle="modal" data-target="#modalHelpProperty"></button>
            </div>
          </div>
        </div>
        <div class="list-group">
          <div class="list-group-item">
            <div class="row">
              <div class="col-xs-6">
                <a href="#" class="slider-title" data-toggle="modal" data-target="#modalProperty">Cargo</a>
              </div>
              <div class="col-xs-6">
                <div class="range-slider-group">
                  <div class="range-slider-input">
                    <input type="range" min="0" max="100" step="1" value="80">
                  </div>
                  <div class="range-slider-value">
                    <span class="slider-value"></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="list-group-item">
            <div class="row">
              <div class="col-xs-6">
                <a href="#" class="slider-title" data-toggle="modal" data-target="#modalProperty">Segmento</a>
              </div>
              <div class="col-xs-6">
                <div class="range-slider-group">
                  <div class="range-slider-input">
                    <input type="range" min="0" max="100" step="1" value="10">
                  </div>
                  <div class="range-slider-value">
                    <span class="slider-value"></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="list-group-item">
            <div class="row">
              <div class="col-xs-6">
                <a href="#" class="slider-title" data-toggle="modal" data-target="#modalProperty">Tamanho (colaboradores)</a>
              </div>
              <div class="col-xs-6">
                <div class="range-slider-group">
                  <div class="range-slider-input">
                    <input type="range" min="0" max="100" step="1" value="11">
                  </div>
                  <div class="range-slider-value">
                    <span class="slider-value"></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="panel-footer text-left">
          <div class="row">
            <div class="col-xs-6">
              <a href="#" class="btn-height-sm" data-toggle="modal" data-target="#modalProperty"><i class="xicon-plus"></i> Adicionar propriedade</a>
            </div>
            <div class="col-xs-6 text-right">
              <span class="btn-height-sm slider-value-total">Total: <span class="text-danger">101%</span></span>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

<%= render :partial => 'lead_scoring/add_property' %>

<%= render :partial => 'lead_scoring/modal_help' %>

<% content_for :actions_footer do %>
<div class="actions-footer">
  <div class="container">
    <%= link_to "Voltar", lead_scoring_index_path, :class => 'btn btn-link pull-left' %>
    <%= link_to "Descartar alterações", lead_scoring_rules_fit_path, :class => 'btn btn-link' %>
    <%= link_to "Salvar", lead_scoring_rules_fit_path, :class => 'btn btn-default' %>
    <%= link_to "Salvar e avançar", lead_scoring_rules_interest_path, :class => 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/lead_scoring/rules_interest.html.erb
<div class="row">
  <div class="col-xs-3">
    <p class="help-block">Alinhe junto ao seu time de vendas quais as propriedades que melhor representam um Lead pronto para venda.</p>
    <p class="help-block">Você também pode utilizar os dados do <%= link_to "Marketing BI", "" %> para descobrir os termos mais relevantes entre os seus clientes para cada propriedade.</p>
  </div>
  <div class="col-xs-9">
    <form class="form-inline">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="row row-nogutter">
            <div class="col-xs-9">
              <h3 class="panel-title">Grupos de pontuação</h3>
            </div>
            <div class="col-xs-3 text-right">
              <button type="button" class="panel-heading-btn popover-info" data-toggle="modal" data-target="#modalHelpProperty"></button>
            </div>
          </div>
        </div>
        <ul class="list-group">
          <li class="list-group-item data-group">
            <div class="row">
              <div class="col-xs-8">
                <h4 class="data-title"><a href="#" data-toggle="modal" data-target="#modalProperty">ToFu</a></h4>
              </div>
              <div class="col-xs-4 text-right">
                <span class="data-value">5 <small>pontos</small></span>
              </div>
            </div>
          </li>
          <li class="list-group-item data-group">
            <div class="row">
              <div class="col-xs-8">
                <h4 class="data-title"><a href="#" data-toggle="modal" data-target="#modalProperty">MoFu</a>
              </div>
              <div class="col-xs-4 text-right">
                <span class="data-value">10 <small>pontos</small></span>
              </div>
            </div>
          </li>
          <li class="list-group-item data-group">
            <div class="row">
              <div class="col-xs-8">
                <h4 class="data-title"><a href="#" data-toggle="modal" data-target="#modalProperty">BoFu</a></h4>
              </div>
              <div class="col-xs-4 text-right">
                <span class="data-value">25 <small>pontos</small></span>
              </div>
            </div>
          </li>
          <li class="list-group-item data-group">
            <div class="row">
              <div class="col-xs-8">
                <h4 class="data-title"><a href="#" data-toggle="modal" data-target="#modalProperty">Levantadas de mão</a>
              </div>
              <div class="col-xs-4 text-right">
                <span class="data-value">75 <small>pontos</small></span>
              </div>
            </div>
          </li>
        </ul>
        <div class="panel-footer text-left">
          <a href="#" class="btn-height-sm" data-toggle="modal" data-target="#modalProperty"><i class="xicon-plus"></i> Adicionar propriedade</a>
        </div>
      </div>
    </form>
  </div>
</div>

<%= render :partial => 'lead_scoring/add_convertion' %>

<% content_for :actions_footer do %>
<div class="actions-footer">
  <div class="container">
    <%= link_to "Voltar", lead_scoring_rules_fit_path, :class => 'btn btn-link pull-left' %>
    <%= link_to "Descartar alterações", lead_scoring_rules_interest_path, :class => 'btn btn-link' %>
    <%= link_to "Salvar", lead_scoring_rules_interest_path, :class => 'btn btn-default' %>
    <%= link_to "Salvar e sair", lead_scoring_index_path, :class => 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/lead_scoring/rules_segmentation.html.erb
<p>segmentation</p>

app/views/lead_scoring/show.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'lead_scoring' %>
<% end %>

<% content_for :pagetitle do %>
  <%= link_to "Lead Scoring", lead_scoring_index_path %>
<% end %>

<% content_for :pagesubtitle do %>
  <h2>Analisar</h2>
<% end %>

<div class="container">
  <div class="container-nav-pills">
    <ul class="nav nav-pills">
      <li class="active"><%= link_to "Propriedades do Lead", "javascript:void(0);" %></li>
      <li class=""><%= link_to "Conversões", "javascript:void(0);" %></li>
      <li class="disabled"><%= link_to "Emails", "javascript:void(0);" %></li>
      <li class="disabled"><%= link_to "Fluxos de automação", "javascript:void(0);" %></li>
    </ul>
  </div>

  <div id="properties">
    <%= render :partial => 'lead_scoring/show_properties' %>
  </div>

  <div id="conversions" class="hide">
    <%= render :partial => 'lead_scoring/show_conversions' %>
  </div>

</div>

<% content_for :footer do %>
  <script>

  </script>
<% end %>

app/views/lead_scoring/steps/automation.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'lead_scoring' %>
<% end %>

<% content_for :pagetitle do %>
  <%= link_to "Lead Scoring", lead_scoring_index_path %>
<% end %>

<% content_for :pagesubtitle do %>
  <h2>Configurar</h2>
<% end %>

<% content_for :footer do %>
 <%= javascript_include_tag 'lead_scoring' %>
<% end %>

<div class="container">
  <%= render :partial => 'lead_scoring/steps/navbar' %>
  <p>Editar</p>
</div>